# -*- coding: utf-8 -*-
db.define_table('UploadDB',
                Field('UserId', default=auth.user_id, readable=True, writable=False),
                Field('Name', readable=True, writable=False),
                Field('TarFile', 'upload', default='path/',requires=IS_NOT_EMPTY()),
                Field('CompiledAt','datetime', writable=False),
                Field('CompileErrorLog','text',writable=False),
                Field('CompileOutLog','text',writable=False),
                Field('SubmissionTime','datetime', default=request.now, writable=False),
                Field('Evaluation_Started_At','datetime', writable=False),
                Field('Evaluated_At','datetime', writable=False),
                Field('Score','integer',writable=False),
                Field('TestCase1Log','text',writable=False),
                Field('TestCase2Log','text',writable=False),
                Field('TestCase3Log','text',writable=False),
                Field('TestCase4Log','text',writable=False),
                Field('TestCase5Log','text',writable=False),
                Field('TestCase1Error','text',writable=False),
                Field('TestCase2Error','text',writable=False),
                Field('TestCase3Error','text',writable=False),
                Field('TestCase4Error','text',writable=False),
                Field('TestCase5Error','text',writable=False),
                Field('Console','text',writable=False),
                Field('Status','string',writable=False))
